### PR TITLE
[PL-133251] fix varnish reload

### PR DESCRIPTION
**Pull request by PhilTaken**
varnish reload was broken before when there was more than 0 cold vcls since the $vadm variable is empty. changing it to ${vadm} properly templates the path to the varnish admin binary using nix.

this does not immediately break varnish but leaves cold vcls lying around. a restart will remove all cold vcls anyways and a consecutive reload would also mark the system as failed but load new vcls as intended besides discarding cold vcls

@flyingcircusio/release-managers

## Release process

- [x] Created changelog entry using `./changelog.sh`

## PR release workflow (internal)

- [x] PR has internal ticket
- [ ] internal issue ID (PL-…) part of branch name
- [x] internal issue ID mentioned in PR description text
- [x] ticket is on Platform agile board
- [x] ticket state set to *Pull request ready*
- [x] if ticket is more urgent than within the next few days, directly contact a member of the Platform team

## Design notes

- [ ] Provide a feature toggle if the change might need to be adjusted/reverted quickly depending on context. Consider whether the default should be `on` or `off`. Example: rate limiting.
- [ ] All customer-facing features and (NixOS) options need to be discoverable from documentation. Add or update relevant documentation such that hosted and guided customers can understand it as well.

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined? (WHERE)
  - fixes reloads when there is > 0 cold vcls
- [x] Security requirements tested? (EVIDENCE)
  - tested on test vm

### CODE REVIEW

**Review by ctheune — CHANGES_REQUESTED** [review]
Please improve the changelog.

Also: how did this happen and wasn't caught during development?

**Comment by PhilTaken** [comment]
This is an edge case that only occurs when there are cold vcls to discard. This happened in 9f10ecc9a888f603bfd3df914466fd5d244d207f when vadm was changed from a shell variable to a nix variable for better reuse in another script. Since bash doesn't inform about undefined variables and only substitutes them with an empty string this was not caught immediately

**Comment by ctheune** [comment]
As discussed yesterday: please try to add a test case for this - it's been broken once already and caused issues.

Also: the branch name doesn't include the ticket number and the changelog entry doesn't either.

**Review by ctheune — CHANGES_REQUESTED** [review]
see my other comment: branch name, ticket number  in changelog, and test case

**Pull request closed without merging**
